# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'github-browser-reswift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for github-browser-reswift
  pod 'ReSwift'
  pod 'ReSwiftRouter'
  pod 'ReSwiftThunk'
  pod 'SAMKeychain'
  pod 'ListKit'

end
