# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tabbar-navigation-reswift-router' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tabbar-navigation-reswift-router
  pod 'ReSwift'
  pod 'ReSwiftRouter'

end
